### <font color='red'> \* 해당 자료의 소스는 '파이썬 라이브러리를 활용한 데이터 분석(Wes Mckinney 지음, 김영근 옮김, 한빛미디어)' 도서의 내용을 기반으로 작성된 내용임을 알립니다.  </font>

[도서정보 확인하기](http://book.naver.com/bookdb/book_detail.nhn?bid=7310391)

In [46]:
from pandas import Series, DataFrame

In [47]:
import pandas as pd

In [48]:
import numpy as np

## Series와 인덱스(index)로 배열 다루기
Series는 일련의 객체를 담을 수 있는 1차원 배열 같은 자료 구조이다(어떤 Numpy 자료형이라도 담을 수 있다).
그리고 색인(index)라고 하는 배열의 데이터에 연관된 이름을 가지고 있다

In [49]:
obj = Series([4,7,-5,3])

In [50]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [51]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [52]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [53]:
obj2 = Series([4,7,-5,3], index = ['d','b','a','c'])

In [54]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [55]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [56]:
obj2['a']

-5

In [57]:
obj2[2]

-5

In [58]:
obj2['a'] = -10

In [59]:
obj2['a']

-10

In [60]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [61]:
obj2*2

d     8
b    14
a   -20
c     6
dtype: int64

In [62]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.000045
c      20.085537
dtype: float64

고정 길이의 정렬된 사전형이라고 이해하는 것이다. 색인 값에 데이터 값을 매핑하고 있으므로 파이썬의 사전형과 비슷하다. 
파이썬의 사전형을 인자로 받아야 하는 많은 함수에서 사전형을 대체하여 사용할 수 있다

In [63]:
'b' in obj2

True

In [64]:
'e' in obj2

False

파이썬 사전형(dictionary)에 데이터를 저장해야 한다면 파이썬 사전 객체로 부터 Series 객체를 생성할 수 있다.  
NaN = not a number

In [65]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000, 'Utah':5000}

In [66]:
obj3 = Series(sdata)

In [67]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [68]:
states = ['California','Ohio','Oregon','Texas']

In [69]:
obj4 = Series(sdata, index = states)

In [70]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

### isnull() and notnull()

isnull()과 notnull()은 pd뿐 아니라 Series의 인스턴트 매서드이기도 하다

In [71]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [72]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [73]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [74]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

### Series 객체의 산술연산 

In [75]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [76]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [77]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

### name 속성

In [78]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [79]:
obj4.name = 'population'
obj4.index.name = 'state'

In [80]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [81]:
obj4.index = ['california','Ohio','Oregon','Texas@@']

In [82]:
obj4

california        NaN
Ohio          35000.0
Oregon        16000.0
Texas@@       71000.0
Name: population, dtype: float64

## DataFrame 다루기

R의 data.frame과 유사한 개념이다.  
DataFrame은 데이터를 내부적으로 2차원 형식으로 저장하므로, 고차원의 표 형식 데이터를 나중에 살펴볼 계층적 색인을 통해 쉽게 표현할 수 있다. 계층적 색인은 pandas에서 데이터를 취급하는 고급 기능에 필수적인 요소이다.  
DataFrame 객체의 생성하는 방법 중 가장 흔한 방법은 같은 길이의 리스트에 담긴 사전을 이용하거나 NumPy 배열을 이용하는 방법이 있다

In [83]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year' : [2000,2001,2002,2001,2002],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9]}
DataFrame(data)

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [84]:
DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [86]:
df = DataFrame(data, columns = ['year','state','pop','debt'])

In [87]:
df

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN

In [88]:
df.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [89]:
df['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

In [90]:
df['debt'] = 16.5

In [91]:
df

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5

In [109]:
df.ix[3]

year       2001
state    Nevada
pop         2.4
debt       -1.5
Name: four, dtype: object

In [93]:
df.index = ['one','two','three','four','five']

In [94]:
df

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [95]:
df.ix['four']

year       2001
state    Nevada
pop         2.4
debt       16.5
Name: four, dtype: object

In [96]:
df['debt'] = np.arange(5)

In [97]:
df

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [98]:
df['debt'] = np.arange(5.)

In [99]:
df

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [100]:
val = Series([-1.2,-1.5,-1.7], index = ['two','four','finve'])

In [101]:
df['debt'] = val

In [102]:
df

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN

In [103]:
df['eastern'] = df.state == 'Ohio'

In [104]:
df

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9   NaN    False

In [105]:
del df['eastern']

In [106]:
df

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN

In [107]:
pop = {'Nevada':{2001:2.4, 2002:2.9}, 'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}

In [108]:
df2 = DataFrame(pop)

In [110]:
df2

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [111]:
df2.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [113]:
df3 = DataFrame(pop, index = [2000,2001,2002,2003])

In [114]:
df3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [141]:
DataFrame({'Ohio' : df2['Ohio'][:-1], 'Nevada' : df2['Nevada'][:2]})

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [142]:
df2.index.name = 'year'
df2.columns.name = 'state'

In [143]:
df2

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

Series와 유사하게 values 속성은 2차원 배열로 반환함

In [145]:
df2.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [146]:
df.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, nan]], dtype=object)

#### DataFrame 생성자에서 사용 가능한 입력 데이터

|       형                   |                      설명                                            
| :---                       |:----------------------------------------------------------------------
|  2차원 ndarray              | 데이터를 담고 있는 행렬, 선택적으로 row와 column의 이름을 전달할 수 있다. 
|  배열, 리스트, 튜플의 사전   | 사전의 모든 항목은 같은 길이를 가져야 하며, 각 항목의 내용이 DataFrame의 칼럼이 된다 
|  NumPy의 구조화 배열        | 배열의 사전과 같은 방식으로 취급된다. 
|  Series 사전                | Series의 각 값이 칼럼이 된다. 명시적으로 색인을 넘겨주지 않으면 각 Series의 색인이 하나로 합쳐져서 row의 색인이 된다 
|  사전의 사전                | 내부에 있는 사전이 칼럼이 된다. 키 값은 'Series 사전'과 마찬가지고 합쳐져 row의 색인이 된다  
|  사전이나 Series의 리스트    | 리스트의 각 항목이 DataFrame의 row가 된다. 합쳐진 사전의 키 값이나 Series의 색인이 DataFrame 칼럼의 이름이 된다.  
| 리스트나 튜플의 리스트        | '2차원 ndarray'와 동일함 
| 다른 DataFrame              | 색인이 따로 지정되지 않는다면 원 DataFrame의 색인이 그대로 사용됨
| Numpy MaskedArray           | '2차원 ndarray'와 같은 방식으로 취급되지만 마스크 값은 반환되는 DataFrame에서 NA 값이 된다. 

### Index object(색인 객체)

테이블 형식의 데이터에서 row/column의 이름, 축의 이름 등의 다른 metadata 를 저장하는 객체

In [159]:
obj = Series(range(3), index = ['A','B','C'])
obj

A    0
B    1
C    2
dtype: int32

In [161]:
obj.index = ['a','b','c']
obj

a    0
b    1
c    2
dtype: int32

In [163]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [165]:
index[1:]

Index(['b', 'c'], dtype='object')

**(중요) index 객체는 변경할 수 없으며, 자료 구조 사이에서 안전하게 공유될 수 있다**  
아래에서 예제에서 에러 발생됨.  
사용자는 index 객체에 대해 자세히 몰라도 되지만 Index 객체는 pandas의 데이터 모델에서 매우 중요하다

In [180]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [170]:
np.arange(3)

array([0, 1, 2])

In [171]:
index2 = pd.Index(np.arange(3))
index2

Int64Index([0, 1, 2], dtype='int64')

In [173]:
Series([1.5, -2.5, 0])

0    1.5
1   -2.5
2    0.0
dtype: float64

In [175]:
obj2 = Series([1.5, -2.5, 0], index = index2)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [178]:
obj2.index

Int64Index([0, 1, 2], dtype='int64')

In [179]:
obj2.index is index2

True

#### pandas의 주요 index 객체

|       class    |                      Description                                            
| :---           |:----------------------------------------------------------------------
|  Index         | 가장 일반적인 index객체이며, 파이썬 객체의 NumPy 배열형식으로 축의 이름을 표현
|  Int64Index    | 정수값을 위한 특수한 Index 
|  MultiIndex    | 단일 축에 여러 단계의 색인을 표현하는 계층적 색인 객체, 튜플으 ㅣ배열과 유사하다고 볼 수 있다 
|  DatetimeIndex | 나노초 타임스템프를 저장한다(NumPy의 datetime64 dtype으로 표현된다)  
|  PeriodIndex   | 기간 데이터를 위한 특수한 Index 


In [183]:
df3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [184]:
'Ohio' in df3.columns

True

In [185]:
'2001' in df3.index

False

In [186]:
2001 in df3.index

True

#### Index method and attributes

|       Metho    |                      Description                                            
| :---           |:----------------------------------------------------------------------
|  affend        | 추가적인 Index 객체를 덧붙여 새로운 색인을 반환
|  diff          | 색인의 차집합을 반환 
|  intersection  | 색인의 교집합을 반환
|  union         | 색인의 합집합을 반환
|  isin          | 넘겨받은 값이 해당 색인 위치에 존재하는지 알려주는 불리언 배열을 반환
|  delete        | i 위치의 색인이 삭제된 새로운 색인을 반환
|  drop          | 넘겨받은 값이 삭제된 새로운 색인을 반환
|  insert        | i 위치에 값이 축가된 새로운 색인을 반환
|  is_monotonic  | 색인이 단조성을 가진다면 True 반환
|  is_unique     | 중복된는 색인이 없다면 True 반환
|  unique        | 색인에서 중복되는 요소를 제거하고 유일한 값만을 반환